### ISSUE TITLE
ERROR : (api_server) 現在地情報から guest_item を検索すると 500 が出る

### ISSUE THREAD

**Issue by Yoshiharu-Ikutani** [colorfultalk/ct_prototype#20]
エラー文を貼り付ける

```
2017-10-03T05:47:43.119174+00:00 app[web.1]: Internal Server Error: /api/guest-searchitems/
2017-10-03T05:47:43.119185+00:00 app[web.1]: Traceback (most recent call last):
2017-10-03T05:47:43.119187+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
2017-10-03T05:47:43.119189+00:00 app[web.1]: KeyError: 'latitude'
2017-10-03T05:47:43.119188+00:00 app[web.1]:     list_ = super(MultiValueDict, self).__getitem__(key)
2017-10-03T05:47:43.119189+00:00 app[web.1]:
2017-10-03T05:47:43.119190+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2017-10-03T05:47:43.119191+00:00 app[web.1]:
2017-10-03T05:47:43.119191+00:00 app[web.1]: Traceback (most recent call last):
2017-10-03T05:47:43.119192+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2017-10-03T05:47:43.119193+00:00 app[web.1]:     response = get_response(request)
2017-10-03T05:47:43.119193+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2017-10-03T05:47:43.119194+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2017-10-03T05:47:43.119195+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2017-10-03T05:47:43.119196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2017-10-03T05:47:43.119195+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2017-10-03T05:47:43.119196+00:00 app[web.1]:     return view_func(*args, **kwargs)
2017-10-03T05:47:43.119197+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/viewsets.py", line 86, in view
2017-10-03T05:47:43.119198+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2017-10-03T05:47:43.119198+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
2017-10-03T05:47:43.119199+00:00 app[web.1]:     response = self.handle_exception(exc)
2017-10-03T05:47:43.119199+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
2017-10-03T05:47:43.119200+00:00 app[web.1]:     self.raise_uncaught_exception(exc)
2017-10-03T05:47:43.119201+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
2017-10-03T05:47:43.119201+00:00 app[web.1]:     response = handler(request, *args, **kwargs)
2017-10-03T05:47:43.119202+00:00 app[web.1]:     lat_max = float(req["latitude"])  + lat_per_100m
2017-10-03T05:47:43.119202+00:00 app[web.1]:   File "/app/api/views.py", line 185, in search_item
2017-10-03T05:47:43.119203+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
2017-10-03T05:47:43.119203+00:00 app[web.1]:     raise MultiValueDictKeyError(repr(key))
2017-10-03T05:47:43.119204+00:00 app[web.1]: django.utils.datastructures.MultiValueDictKeyError: "'latitude'"
2017-10-03T05:47:43.151525+00:00 app[web.1]: [03/Oct/2017 05:47:43] "GET /api/guest-searchitems/?%7B%22longitude%22:%2035,%20%22latitude%22:%20134%7D HTTP/1.1" 500 14449
```

**Comment by Yoshiharu-Ikutani** [comment]
おそらくここらへんか？
views.py の 177行目以降

```
    def search_item(self, request, *args, **kwargs):
        req = request.query_params.copy()
        lat = 0.0090133729745762   # latitude per 1km
        lon = 0.010966404715491394 # longitude per 1km

        lat_per_100m = lat / 10.0
        lon_per_100m = lon / 10.0

        lat_max = float(req["latitude"])  + lat_per_100m
        lat_min = float(req["latitude"])  - lat_per_100m
        lon_max = float(req["longitude"]) + lon_per_100m
        lon_min = float(req["longitude"]) - lon_per_100m
```

**Comment by Yoshiharu-Ikutani** [comment]
GET で渡している QueryDict が変なことになっている可能性あり

```
2017-10-07T03:13:47.496559+00:00 app[web.1]: <QueryDict: {'{"longitude": 34.73, "latitude": 135.73}': ['']}>
```
