### ISSUE TITLE
bug: showフロー

### ISSUE THREAD

**Issue by mkeeda** [colorfultalk/ct_prototype#42]
見つけたshowフローのバグを書いておく

## name 'sample' is not defined
#35 を適用後，showコマンドを押すとエラーが出る

```
[2017-10-31 18:17:18,279] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "chatbot.py", line 66, in callback
    handler.handle(body, signature)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/linebot/webhook.py", line 227, in handle
    func(event)
  File "chatbot.py", line 131, in handle_message
    flow_swicher(event, session, flow)
  File "chatbot.py", line 196, in flow_swicher
    show_flow.show_items(event, session)
  File "/Users/ippeimukaida/Program/python/ct_prototype/flow/show.py", line 31, in show_items
    items.append(sample)
NameError: name 'sample' is not defined
127.0.0.1 - - [31/Oct/2017 18:17:18] "POST /callback HTTP/1.1" 500 -
```

## そもそも`search_my_guest_items()`が404エラーになる
`api/guest-myitems/`に送るパラメータ`guestId`だが，APIサーバ内では`lineId`で検索するコードになっている．
そのため，`guestId`では検索に失敗する．

## showするitem が古いものから5件になっている
`api/guest-myitems/`で取得したjsonは古いものから順に並んでいる．
その先頭5件を表示しているので，古いもの5件が表示されてしまっている．
jsonの後ろから5件を取らないといけない．

## カルーセルのサムネイル画像のURLが参照できないとカルーセルが表示されない？
こんなエラーが起きる．
URLをちゃんと参照できるものにすればエラーは起きない．
```
[2017-11-01 01:50:32,215] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "chatbot.py", line 67, in callback
    handler.handle(body, signature)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/linebot/webhook.py", line 227, in handle
    func(event)
  File "chatbot.py", line 143, in handle_message
    flow_swicher(event, session, flow)
  File "chatbot.py", line 198, in flow_swicher
    show_flow.show_items(event, session)
  File "/Users/ippeimukaida/Program/python/ct_prototype/flow/show.py", line 57, in show_items
    self.line_bot_api.reply_message(event.reply_token, reply_msg)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/linebot/api.py", line 94, in reply_message
    '/v2/bot/message/reply', data=json.dumps(data), timeout=timeout
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/linebot/api.py", line 262, in _post
    self.__check_error(response)
  File "/Users/ippeimukaida/.pyenv/versions/colorful-talk/lib/python3.6/site-packages/linebot/api.py", line 271, in __check_error
    raise LineBotApiError(response.status_code, error)
linebot.exceptions.LineBotApiError: <LineBotApiError [A message (messages[0]) in the request body is invalid]>
```

**Comment by mkeeda** [comment]
たぶん，show.pyの31行目は`self.sample`

**Comment by mkeeda** [comment]
guestの特定はline idではなくguest idでするように統一
